### ISSUE TITLE
The action "Run AppleScript" encountered an error

### ISSUE THREAD

**Issue by coolrecep** [chris1111/MacOS-Disk-Creator#4]
This is what happens as soon as I choose Install macOS Sierra App.

![image](https://cloud.githubusercontent.com/assets/13221472/24585223/db52f9c2-178d-11e7-99c8-565ded35015d.png)

**Comment by chris1111** [comment]
What is your Mac OS system  ?
Not working on VM

**Comment by coolrecep** [comment]
It is a VM, Sierra 10.12.4 . Thank you for the info.

**Comment by chris1111** [comment]
NOT Working on Vm !
